### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ShiroYasha139** [gamemann/XDP-Firewall#17]
Hello, I'm trying to use this firewall to protect my HLDS server against attacks. Below is my xdpfw.conf file

```
interface = "eth0";
updatetime = 15;

filters = (
    {
        enabled = true,
        action = 0,
        pps = 10000,
        blocktime = 600,
        udp_enabled = true,
        udp_dport = 27015
    }
);
```

Is this config correct or will i need to do some changes as at the moment I'm trying to test it alone, below is what I see after starting the process. Even though I connect to the server I don't see any changes in Packets Allowed nor Packets dropped

```
root@ip-172-26-1-240:/etc/xdpfw# sudo xdpfw
libbpf: Kernel error message: Underlying driver does not support XDP in native mode
Could not attach with DRV/native mode (Operation not supported)(-95).
Loaded XDP program in SKB/generic mode.
Packets Allowed: 0 | Packets Dropped: 0
```

Also how do I get back to see the stats if I use Ctrl+C or Ctrl+Z to exit from the program. Using screen doesn't seem to work, program runs but screen doesnt.  Even if I stop the service with systemctl to test again with a different config, I cannot run the program again as it says it's already running.

Thank you.

**Comment by gamemann** [comment]
Hey!

I apologize for the long delay. I've been dealing with personal issues and haven't worked on my open-source projects much recently.

The packet counters are only for rules. In the rule above, you have it set so if you have 10K PPS >, it will *block* the packet. Since this isn't an allow rule, you aren't going to see those counters increment. The only time you will see it is if you start sending 10K+ PPS worth of UDP traffic to the firewall. This seems like an understandable filter for HLDS traffic, though.

As for the error you're receiving, this should have been fixed with issue #15. However, you can force the XDP program to be unloaded with `ip link set <interface name> xdp off` or `ip link set <interface> xdpgeneric off` if it attaches with the XDP generic hook.

I hope the above helps!

**Comment by ShiroYasha139** [comment]
> 

Hi, thanks for your reply, I understand everyone have their problems.

Is there any way I can log IPs that get blocked through the filter I have set? I don't see any change to the filters most of the time, even when I receive a query flood on my HLDS server and I cant monitor it all the time. 
Understood for how to unload the program.

**Comment by gamemann** [comment]
Hey, I'm sorry for the really late reply! A lot has gone on the past few months.

> Is there any way I can log IPs that get blocked through the filter I have set? I don't see any change to the filters most of the time, even when I receive a query flood on my HLDS server and I cant monitor it all the time.
Understood for how to unload the program.
As of right now, nothing is technically logged. I could technically scan the block BPF map in the user-space, but I think BPF tracing would be a lot more better here, I've haven't learned it yet though. I'm going to be making a new project that reports suspicious traffic and such to a back-end and then I'm going to to display it on my TV via my Raspberry Pis. I plan on making it open-source as well and I think that'll be useful in your case since I plan on using BPF tracing with XDP :)

> Also is it necessary to add a source ip for the rule?
If all the malicious traffic is coming from a single or small list of IPs, then yes. However, you also have to remember a lot of traffic, especially UDP, is spoofed. There are many attacks that do not spoof the IPs, though, so it's something worth looking into at least.

I've also implemented some changes to the XDP Firewall today that may fix all the issues you've been having with it it :)

**Comment by ShiroYasha139** [comment]
Hey thanks for the reply. Yeah, I did thought I have to give up. I think logging would help. 

I'm actually getting UDP flood with lots of spoofed IP addresses. What would be the ideal config for it? I did mess around and it was either adding my own IP or the local IP of the AWS Lightsail server I host HLDS on. I mean I added a simple config with my own IP and pps with low value. 
How would I go for the same when I don't know what source IP will be? 

My config is pretty much the same except I changed pps = 5000, I'm hoping it works.
I haven't seen any changes in Packet Dropped even though server lags at times, maybe it's just HLDS stuff now what I'm seeing, it's been only a day since I updated after all.
and I'm getting this when I check status through systemctl, is it a fault from my side?

```
● xdpfw.service - XDP Firewall tool.
     Loaded: loaded (/etc/systemd/system/xdpfw.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-09-06 18:18:57 IST; 7min ago
    Process: 1316 ExecStart=/usr/bin/xdpfw (code=exited, status=1/FAILURE)
    Process: 1317 ExecStopPost=/bin/bash -c ip link set dev $(grep -E ^interface /etc/xdpfw/xdpfw.conf | sed -En 's/^.+=|["; ]//gp') xdp off (code=exited, status=0/SUCCESS)
   Main PID: 1316 (code=exited, status=1/FAILURE)

Sep 06 18:18:57 ip-172-26-11-48 systemd[1]: xdpfw.service: Scheduled restart job, restart counter is at 6.
Sep 06 18:18:57 ip-172-26-11-48 systemd[1]: Stopped XDP Firewall tool..
Sep 06 18:18:57 ip-172-26-11-48 systemd[1]: xdpfw.service: Start request repeated too quickly.
Sep 06 18:18:57 ip-172-26-11-48 systemd[1]: xdpfw.service: Failed with result 'exit-code'.
Sep 06 18:18:57 ip-172-26-11-48 systemd[1]: Failed to start XDP Firewall tool..
```
