### ISSUE TITLE
Loading xdpfw in offload/hardware mode

### ISSUE THREAD

**Issue by Firewallv2** [gamemann/XDP-Firewall#20]
when trying to load the xdpfw program using offload/hardware mode using the command xdpfw --offload i get the error 

libbpf: map 'filters_map': failed to create: Invalid argument(-22)
libbpf: failed to load object '/etc/xdpfw/xdpfw_kern.o'
Could not load XDP BPF program :: Invalid argument.
Error loading eBPF object file. File name => /etc/xdpfw/xdpfw_kern.o.

Do you Know How to fix this error so it will load in offload/hardware mode?

**Comment by gamemann** [comment]
Hey, I apologize for the delay!

What NIC are you using with offload mode? Unfortunately, NICs have even stricter BPF size limitations for offloading since the NICs don't have as much memory. I ran into this issue a few times with Netronome NICs, but with another XDP program which worked fine in DRV mode, but not offload mode. Therefore, it may not be possible to run this full program with offload mode.

Thank you.
