### ISSUE TITLE
Customise This Program For My Requirements

### ISSUE THREAD

**Issue by Firewallv2** [gamemann/XDP-Firewall#21]
Is it possible to add The Following To This Program Custom For My Needs Such As ; Layer 3. The rest of the tcp flags. Port ranges. Ip ranges. States and packet tracking. I will pay You If You Could Do That .

**Comment by gamemann** [comment]
Hey! I'm sorry for the late reply.

Unfortunately, I don't have much time right now with a big project/job I'm working on and I also signed some contracts at previous jobs when doing (D)DoS protection/mitigation where I'm not sure I would be able to implement the above due to non-compete agreements and such (lasts a year or two). When I do have time and those contracts are cleared, I would really like to revisit this. Anybody is welcomed to do pull requests implementing those features to this firewall as well :)
