### ISSUE TITLE
Adding some features for prevent DDoS

### ISSUE THREAD

**Issue by XEONNET** [gamemann/XDP-Firewall#23]
This project is awesome.

I'm looking for Prevention DDoS using XDP Firewall.

Can you add Threshold?

Set Max Throughput and automatically write WhiteListed IPs while under Max Throughtput.

in this case, when DDoS Occurred, WhiteListed IPs can connect to server and others will not.

this will be good and helpful features for Home and Small Buisiness Users.

**Comment by gamemann** [comment]
Hey and thank you! I'm sorry for the very late reply on this, I haven't seen this until today and the last few months have been hectic.

These would be some interesting features I'd like to implement in the future when I have the time. Unfortunately, my time is very limited for the firewall since I am working on a few other big projects at the moment.

I also hope to make an all-in-one router and firewall in the future that'll utilize XDP called [NetConn](https://github.com/deaconn-net/netconn). This is the project I'll likely implement these features into since it's going to be combining both my XDP firewall and forwarding program with a GUI.
