### ISSUE TITLE
thx for the mit license

### ISSUE THREAD

**Issue by hiqsociety** [gamemann/XDP-Firewall#29]
pls put a sponsor or buy a coffee link too. thx

**Comment by gamemann** [comment]
No problem and I applied for the sponsorship program today after I saw this. I will let you know when everything is approved :smiley:

**Comment by ultperf** [comment]
@gamemann ur work is great but it seems to be a lonely journey though coz not many are in xdp stuff (that i can find online).

by the way can u help out with this for ubuntu 22.04?

i cant seem to find how to install xdp-tools for ubuntu 22.04 and stuck there
https://github.com/xdp-project/xdp-tools/issues/246

pls help this out. i will be the first to sponsor u when u r approved.

**Comment by gamemann** [comment]
Hey, just wanted to let you know you may now sponsor me if you'd like.

@ultperf It looks like you made progress on that issue since your last comment. What issues are you now facing? Also I saw you're talking to Toke, they've helped me a lot with XDP in the past on the XDP Newbies mailing list and their knowledge is far beyond mine when it comes to XDP and the Linux kernel (not to mention they're just a good person in general from my experience!).

I also agree on the lonely journey part, there aren't many network programmers in general and XDP is still very new/complicated to most. To be honest, I went through a lot of pain learning XDP, but that's why I published most of my stuff open-source in hopes that it'll help others and others won't have to go through the same issues I had. I highly recommend the XDP Newbies [mailing list](https://www.spinics.net/lists/xdp-newbies/) as well since the XDP maintainer and developers are active there and they helped me a lot in the past.
