### ISSUE TITLE
Cidr/Subnet support & Some small things

### ISSUE THREAD

**Issue by Gawnz1** [gamemann/XDP-Firewall#36]
Hello, is it possible to add a Cidr/subnet support?
Like: 11.11.11.11/22 or ip/24
A whitelist for certain ips would be also good.
Some statistics for dropped packets like a gui or dropped packets per sec while attack is going on would be also good.
Awsome project. Keep it up :)

**Comment by gamemann** [comment]
Hey, I'm sorry for the very long delay! I may add CIDR support in the future, but I'm not sure on an ETA due to how busy my life has been recently.

I've implemented a lot of this functionality into software I made [here](https://github.com/gamemann/Kilimanjaro), but I no longer work on that project. If you're interested in implementing this functionality, code in the repository I linked should definitely help, though.
