### ISSUE TITLE
this project have problem botnet attack 50-100Mpps

### ISSUE THREAD

**Issue by namecloudz** [gamemann/XDP-Firewall#45]
i have problem ddos attack 50-100mpps

xdp-firewall drop all connection is not processing.

    {
        enabled = true,
        action = 0,

        udp_enabled = true,
        pps = 500,
        blocktime = 300
    }
    
    
drop only 988 packet every have attack.

how to fix or optimize?

**Comment by gamemann** [comment]
Hey, are you able to retrieve packet captures of the attack? My assumption is they're using spoofed IPs/random ports. If this is the case, the reason it is not blocking properly is because the BPF map used to store IP blocks relies on a single source IP as the key. Therefore, if the IPs are random/spoofed, there are going to be many entries in the map from the attack, but a majority of them won't exceed 500 PPS.

This is where a stateful firewall would be most effective since the goal in that case is to allow traffic that the firewall validates via handshakes between the client and server, and drop all other traffic. Unfortunately, I don't have the time to make this firewall stateful and I'm also currently very limited due to NDAs I've signed in the past for jobs and such so I can't write open-source layer-7 filters.

Unfortunately, this firewall may not have the functionality to block the type of attack you're receiving if the packet's characteristics are completely randomized. I won't say for sure until you provide a packet capture since there may be other characteristics such as the length of packets, TTL, etc. that separate the attack from legitimate traffic you can use in this firewall to block/drop the attack. If you aren't comfortable sending the packet capture in this issue due to privacy reasons, you may send it to me through a DM on an application such as Discord or through email if you'd like.

**Comment by namecloudz** [comment]
you can give discord link?

**Comment by gamemann** [comment]
Sure! My username is `gamemann`, or you can join my Deaconn [server](discord.deaconn.net).
